package com.wordscapes.puzzle.data.level

import kotlinx.serialization.Serializable

/**
 * Wire format for `assets/levels.json`, generated by `tools/generate_levels.py`.
 *
 * These types mirror the JSON exactly and carry no logic. Everything derived —
 * cell occupancy, intersections, bounds checking — happens in [LevelMapper] on
 * the way to the domain model, so the DTO stays a dumb, obviously-correct
 * transcription of the file on disk.
 */
@Serializable
data class LevelsFileDto(
    val levels: List<LevelDto>,
)

@Serializable
data class LevelDto(
    val id: Int,
    val letters: List<String>,
    val gridWidth: Int,
    val gridHeight: Int,
    val words: List<PlacedWordDto>,
)

@Serializable
data class PlacedWordDto(
    val word: String,
    val row: Int,
    val col: Int,
    val horizontal: Boolean,
)
